---
title: How disturbance affects the establishment of new polyploid plant species
author: Rose McKeon
date: "March 2019"
bibliography: assets/ploidy.bib
bibliographystyle: assets/crumpetBES.bst
output: 
  word_document:
  pdf_document:
    template: assets/crumpet_proposal.tex
    citation_package: natbib
    keep_tex: no
    fig_caption: yes
    fig_width: 2.5
    fig_height: 2.5
    latex_engine: xelatex
---


# Summary

Polyploidisation is thought to be fundamental in the diversification of plant species. Both mutation and hybridisation that leads to additional sets of chromosomes (polyploidy) are commonplace in plant taxa, having occurred in almost all lineages. While polyploids have been studied for over a century, the factors that drive the success of their establishment in the face of reproductive disadvantages and high extinction rates are still unclear. Polyploids are often recorded in recently disturbed locations, but exactly how distrubance may affect the establishment of polyploids has not been clearly addressed. This research will contribute to answering a classic problem of plant biology using a modelling technique that has not yet been applied to the problem.

# Background

Polyploidisation is thought to be fundamental in the diversification of plant species<!--- BD: Would @Ramsey2014 work here? --->. Plants have an extremely high tolerance for polyploidy and it is a ubiquitous feature in the lineages of most plant taxa<!--- BD: Might be useful to have a reference here too -- even if it's @Ramsey2014 again --->. Furthermore, polyploidisation often causes saltational speciation and is found to coincide with a large proportion of speciation events [@Wood2009]. However, studies on the extinction rates of polyploids suggest that many of these new lines are evolutionary dead ends that tend to become extinct at the establishment phase due to reproductive disadvantages [@Arrigo2012]. Therefore, understanding demographics at the establishment phase is critical to predicting polyploidisation of plant species. <!--- BD: Might want to swap the preceding and subsequent seentences? ---> Reproductive disadvantages include lack of mates, diploid pollen swamping, and triploid sterility. There are benefits, however, which may offset these costs. Polyploids are frequently linked with distinct traits such as "gigas effects", which include increases in plant organs, reversal of selfing inhibition, enhanced capabilities for buffering of deleterious mutation (due to increased heterozygosity), and hybrid vigour (heterosis) [@Woodhouse2009; @Ramsey2014]. These traits are thought to overcome the reproductive disadvantages of polyploidy and instead make this mutation key to the invasive and adaptive potential of plants<!--- BD: Maybe an end clause here that links back to plant diversification? E.g., ", ultimately shaping broader patterns of plant diversification"? --->.

>**Despite the long-term study of polyploidy in plant taxa, fundamental questions regarding demographic establishment and mediation of adaptation to new environments are yet to be understood**. 

Polyploids can be organised into two broad groups: autopolyploid and allopolyploid. Autoployploids arise mitotically via genome duplication events during gametogenesis in selfing individuals, whereas allopolyploids arise meiotically from unreduced gametes via hybridization of sexually reproducing individuals. In natural populations, both types of polyploid maintain distinct spatial distributions relative to progenitors and other diploids, suggesting the importance of polyploidy as a mechanism of ecological divergence. However, recent niche modelling has not supported this theory and proposes that glacial retreat and environmental disturbance may be more influential [@Godsoe2013]. This study will focus on disturbance as a predictive factor of polyploid establishment. <!--- BD: More broadly (relative to Mario's comments), could this be shortened a bit to give more space for the methodology. It seems like all you really need is a key sentence that suggests that disturbance is influential in predicting polyploid establishment [@Godsoe2013]. I'm not sure if going into the types of polyploidy is really central to your key question (do correct me if this is wrong!). ---->

# Issue

While polyploids have been studied for over a century, the factors that drive the success of their establishment in the face of reproductive disadvantages and high extinction rates are still unclear. Polyploids are often recorded in recently disturbed locations but disentangling the other processes at play in natural environments has proved difficult [@Ramsey2014]. Due -- in part -- to lack of predictive power with regard to demographics of polyploids, population assignment of these taxa is especially difficult. Elucidating the effect of disturbance on the distribution of polyploids could, therefore, have great importance to those in both forensics and conservation [@Field2017].  <!--- BD: I think a sentence now justifying your IBM approach would be really useful here (room for it if you cut down the space in the previous paragraph. You've nicely explained why the relationship between polyploidy and disturbance has been very difficult to understand. Now hit the reviewer with your novel approach -- using an IBM so that this relationship can be understood by clearly linking the patterns to the processes that you model. --->


# The Research Question

**How does disturbance on a landscape affect the establishment of new polyploid plant species?**

## Methodology

This study aims to determine how environmental disturbance affects polyploid distribution by means of an individual based model (IBM), a method which has not yet been applied to this classic problem of plant biology<!--- BD: The novelty of the approach, I think, should come early -- ideally with just a bit more emphasis on why your approach will be usesful (see previous comment). I think you're nearly there! --->. IBMs model discrete individuals with varied traits and simulate a given process so that resulting patterns can be analysed<!--- BD: I'd rephrase to make more in line with the particular question; e.g., "and simulate biological systems so that biological patterns (e.g., species distributions) can be predicted from underlying biological processes (e.g., polyploidisation)." -- or something like that? I realise this seems repetitive, but you often have to really make the connection obvious for readers who are unfamiliar with the topic.  --->. The model we will create will simulate plant diversification via polyploidisation over time. Disturbance level of the landscape will be manipulated so that patterns of ploidy across the simulated landscape can be anlaysed in relation to disturbance. This will test how important disturbance really is for predicting polyploid distribution. <!--- BD: I agree that more emphasis on the methdos is probably needed here, even if it's just a quick story of what will happen in the model. E.g., plants will be initialised on a spatially explicit landscape, then over generations, polyploidy will arise with some probability. Fitness costs and benefits of polyploidy will be parameterised, then plant diversification will be quantified through simulation across varying levels of disturbance (e.g., mass plant death?) on the landscape. For philosophical reasons, I actually don't like wording theoretical models as if they are hypotheses being tested empirically, but I'm in the minority on this, so I tend to do it anyway when writing grants (less often manuscripts). ---> 


## Results

Results from the model will be analysed and written up as a report. The model itself will be published as an R package which will provide functions that users can utilise to manipulate and run their own simulations. 

>Is it suitable for CRAN? <!--- Absolutely, assuming it's well-written and can pass all CRAN checks (we can worry about this later). There are no content requirements for CRAN, to my knowledge; the package just needs to work --->

If appropriate a poster session and/or interactive web app may also be output.

>I think I'd like to include this for Carnegie as theirs is 12 weeks. <!--- I would definitely say that you're going to present a talk or poster -- they'll want output, with their logo on it as funders. --->


# References


