---
title: Personal Statement
#bibliography: assets/ploidy.bib
#bibliographystyle: assets/crumpetBES.bst
output: 
  #word_document:
  pdf_document:
    template: assets/crumpet_proposal.tex
    citation_package: natbib
    keep_tex: no
    fig_caption: yes
    fig_width: 2.5
    fig_height: 2.5
    number_sections: false
    latex_engine: xelatex
---

This specific research project into polyploid distribution covers a topic which I found inspiring while studying plant ecology. When my tutor first described the problem, and I began to read beyond what he had said, I was fascinated. Firstly by the high tolerance of plants to polyploidy (evident by the frequency of polyploidy in plant communities), and secondly by its colossal impact on plant diversity (evident from the frequency of polyploidisation in most plant lineages). Furthermore, the fact that the distribution of polyploids is still not well understood, despite over a century of research, made this topic even more intriguing.

I have a particular interest in learning biological modelling, and specifically in using Individual-Based Models (IBMs). IBMs are a relatively new technique which have become available to us due to the recent increase in computing power. As such, there are many areas of biology yet to benefit from the insight that they can bring. This classic problem of plant biology is one such problem, and I'm excited to be in a position where I can apply a novel approach to contribute to this field. Additionally, I am eager to learn the technique. I have read that by modelling discrete and varied individuals, fewer assumptions need to be made by a model that deals with data on the individual level (ie: whether plant genomes are polyploid). Manipulation of the biological processes included in the model (polyploidisation) as well as variables of the landscape (in this case, disturbance) can reveal biological patterns and relationships which are otherwise difficult to discern in natural environments. Something I am keen to see first hand.

I find the issue of polyploid distribution an especially intriguing problem as it includes a large genetic component which will be fascinating to learn how to model. Each individual will have a genome which needs to mechanistically mutate so that simulated polyploids appear at a rate that mimics what has been observed in nature. By doing this, I will gain an in-depth understanding of how these processes work during gametogenesis. Furthermore, I find the crux of the issue being an evolutionary cost-benefit analysis particularly exciting. Will the model show that the benefits of polyploid traits outweigh the cost of reproductive disadvantages under varying levels of disturbance?

More broadly, by modelling this system, I will learn a transferrable skill which will help my career in a range of fields. IBMs are frequently used to study problems ranging from genetics and microbiology to ecology and evolution. Modelling is also a skill which I can combine with my past experience as a web developer. Models can be given web interfaces to make them interactive tools; useful in education and in promoting important research. The interface aspect is something I have already contributed to within the department and I am eager to learn how the modelling works so I can fulfil this ambition.