
sequenceDiagram
  participant 1 as Seedlings
  participant 2 as Juveniles
  participant 3 as Adults
  participant F as Ova
  participant M as Pollen
  participant 0 as Seeds
  participant Z as Landscape
  loop Every generation
    Z->>Z: Disturbance
    opt If disturbed
      0->>0: Survival
      1->>1: Survival
      2->>2: Survival
      Note right of 3: There won't be any adults or gametes at the begining of time steps.
    end
    0->>1: Germination
    1->>2: Growth
    2->>3: Growth
    2-->>Z: Clonal growth
    opt If adults
      3->>M: Spermatogenesis
      3->>F: Oogenesis
      Note right of 3: Chance of unreduced gametes causing genome duplication.
      M-->>Z: Dispersal
      alt If pollen meets adults
        M->>F: Fertilisation
        Note left of F: Chance of genome duplication here too?
        alt If fertilisation
          F->>0: Seed/embryo development
          M->>0: Seed/embryo development
          0-->>Z: Dispersal
        else If not
          M-xM: DEATH
        end
      else If not
        M-xM: DEATH
        Note right of M: Pollen that didn't develop into seeds die on failure.
      end
      3-x3: DEATH
      F-xF: DEATH
      Note left of F: Ova that didn't develop into seeds die with adults.
    end
    1->>1: Survival
    2->>2: Survival
    Note right of 2: I'm thinking some persistance of plants through generations might be important for distrubance to have an effect? Can maybe play with the survival chances to test that.
  end