---
title: Landscape Animation
author: "Rose McKeon"
date: "01/08/2019"
output: 
  ioslides_presentation: 
    highlight: espresso
    widescreen: yes
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(tidyverse)
source("R/shiny-setup.R")
sim <- readRDS("data/quick-test-1.rds")
combined <- bind_rows(
    sim$data$seedoutput %>% select(X, Y, gen),
    sim$data$juveniles %>% select(X, Y, gen),
    sim$data$adults %>% select(X, Y, gen),
    # using a new grouping column stops factor binding errors
    .id = "life_stage" 
  )
# now refactor
combined$life_stage <- as.factor(combined$life_stage)
# determine slider size
max_gen <- max(combined$gen)
# and grid size
max_break <- max(combined$X) + 1
max_lim <- max_break + 1
```

---

```{r landscape}
sliderInput(
  "gen", "Generation", 
  min = 1, max = max_gen, value = 1, step = 1, 
  width = "100%",
  animate = animationOptions(
    interval = 2000, loop = F
  )
)

renderPlot({
  this_gen <- combined %>% filter(gen == input$gen)
  ggplot(
    data = this_gen,
      aes(
        x = X + .5,
        y = Y + .5,
        colour = life_stage,
        shape = life_stage,
        alpha = .25
      )
  ) +
  geom_jitter(width = .5, height = .5) +
  scale_x_continuous(
    breaks = seq(0, max_break, by = 10),
    limits = c(0, max_lim),
    minor_breaks = 0:max_break
  ) +
  scale_y_continuous(
    breaks = seq(0, max_break, by = 10),
    limits = c(0, max_lim),
    minor_breaks = 0:max_break
  ) +
  scale_colour_discrete(
    name = "Life stage",
    h = c(20, 180),
    l = 50
  ) +
  scale_shape_discrete(
    name = "Life stage"
  ) +
  theme_classic() +
  theme(
    panel.grid.major = element_line(
      size = .5,
      linetype = "solid",
      colour = "gray"
    ),
    panel.grid.minor = element_line(
      size = .25,
      linetype = "solid",
      colour = "gray"
    ),
    legend.position = "right"
  ) +
  xlab("X") +
  ylab("Y") +
  scale_alpha(guide = F)
},
width = 800
)
```

---

```{r landscape2}
sliderInput(
  "gen2", "Generation", 
  min = 1, max = max_gen, value = 1, step = 1, 
  width = "100%",
  animate = animationOptions(
    interval = 2000, loop = F
  )
)

renderPlot({
  this_gen <- combined %>% filter(gen == input$gen2)
  ggplot(
    data = this_gen,
      aes(
        x = X + .5,
        y = Y + .5,
        colour = life_stage,
        shape = life_stage
      )
  ) +
  geom_count() +
  scale_x_continuous(
    breaks = seq(0, 40, by = 10),
    limits = c(0, 41),
    minor_breaks = 0:40
  ) +
  scale_y_continuous(
    breaks = seq(0, 40, by = 10),
    limits = c(0, 41),
    minor_breaks = 0:40
  ) +
  scale_colour_discrete(
    name = "Life stage",
    labels = c("Seeds", "Juveniles", "Adults"),
    h = c(20, 180),
    l = 50
  ) +
  scale_shape_discrete(
    name = "Life stage",
    labels = c("Seeds", "Juveniles", "Adults")
  ) +
  theme_classic() +
  theme(
    panel.grid.major = element_line(
      size = .5,
      linetype = "solid",
      colour = "gray"
    ),
    panel.grid.minor = element_line(
      size = .25,
      linetype = "solid",
      colour = "gray"
    ),
    legend.position = "right"
  ) +
  xlab("X") +
  ylab("Y") +
  scale_alpha(guide = F)
},
width = 800
)
```